language: ruby
rvm:
  - 2.1.2
sudo: false
env:
  - DB=sqlite
bundler_args: --without development debug
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake test:all
services:
  - redis-server
notifications:
  email:
    - devel@fairmondo.de
before_install:
  - curl -k -L -o elasticsearch-1.3.4.tar.gz https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.4.tar.gz
  - tar -zxvf elasticsearch-1.3.4.tar.gz
  - ./elasticsearch-1.3.4/bin/plugin -install bundle -url http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-plugin-bundle/1.4.0.6/elasticsearch-plugin-bundle-1.4.0.6-plugin.zip
  - ./elasticsearch-1.3.4/bin/elasticsearch 1> /dev/null 2> /dev/null &
