language: ruby
rvm:
  - 2.1.0
env:
  - DB=sqlite
bundler_args: --without development debug
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rspec
notifications:
  email:
    - devel-team@fairnopoly.de
before_install:
  - curl -k -L -o elasticsearch-0.90.3.tar.gz https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.3.tar.gz
  - tar -zxvf elasticsearch-0.90.3.tar.gz
  - ./elasticsearch-0.90.3/bin/plugin --install decompound --url http://bit.ly/1hmvN6Z
  - ./elasticsearch-0.90.3/bin/elasticsearch -f & > /dev/null 
