language: ruby
rvm:
  - 2.1.0
env:
  - DB=sqlite
bundler_args: --without development debug
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - RAILS_ENV=test bundle exec rspec --tag ~search
notifications:
  email:
    - devel-team@fairnopoly.de
services:
  - elasticsearch
