# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9200'
  prefix: 'test'
development:
  host: 'localhost:9200'
production:
  host: '10.0.2.181:9205' # ES 5.4.0
staging:
  host: '10.0.2.177:9205' # ES 5.4.0
