# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9200'
  prefix: 'test'
development:
  host: 'localhost:9200'
production:
  host: '10.0.2.181:9202' #ES 2.3.4
staging:
  host: '10.0.2.181:9200'
