development:
  environment: "sandbox"
  username: "konstantin_api1.fairnopoly.de"
  password: "1393819179"
  signature: "A066BJdsVAQXyiU5hiByGbE9SGY8AWf7Oon3kEqABf01x.17XTSdACKP"
  application_id: "APP-80W284485P519543T"
  #api_cert_file:

test:
  environment: "sandbox"
  username: "sandbox_username"
  password: "sandbox_password"
  signature: "sandbox_signature"
  application_id: "sandbox_app_id"
  api_cert_file: "/path/to_cert"
