---
:concurrency: 40
staging:
  :concurrency: 10
production:
  :concurrency: 20
  :timeout: 30
:queues:
  - [default, 5]
  - [mass_upload, 3]
  - [paperclip_background, 2]
  - [paperclip_foreground, 4]
  - [fastbill, 5]
  - [indexing, 4]
  - [transaction_mails, 6]
