theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontselect,fontsizeselect" 
theme_advanced_buttons2 : "cut,copy,paste,bullist,numlist,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,code,tablecontrols|,forecolor,backcolor"
theme_advanced_buttons3 : ""
theme_advanced_buttons4 : ""
plugins :
  - table